/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lumidt.iyourmusic.userInterface;

/**
 *
 * @author stit_
 */
public class FrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel();
        jMainPSearchM = new javax.swing.JButton();
        jSearchPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSearchPanelBuscas = new javax.swing.JPanel();
        jRBSearchPanelYoutube = new javax.swing.JRadioButton();
        jRBSearchPanelSpofty = new javax.swing.JRadioButton();
        jButtonSPBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jMainPSearchM.setText("Search Music");
        jMainPSearchM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMainPSearchMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jMainPSearchM)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(jMainPSearchM)
                .addGap(54, 54, 54))
        );

        getContentPane().add(jMainPanel, "card2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jSearchPanelBuscas.setBackground(new java.awt.Color(255, 102, 102));
        jSearchPanelBuscas.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jRBSearchPanelYoutube.setText("Youtube");

        jRBSearchPanelSpofty.setText("Spotfy");
        jRBSearchPanelSpofty.setToolTipText("");
        jRBSearchPanelSpofty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonSPBuscar.setText("Buscar");
        jButtonSPBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSPBuscarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jSearchPanelBuscasLayout = new javax.swing.GroupLayout(jSearchPanelBuscas);
        jSearchPanelBuscas.setLayout(jSearchPanelBuscasLayout);
        jSearchPanelBuscasLayout.setHorizontalGroup(
            jSearchPanelBuscasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSearchPanelBuscasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jRBSearchPanelYoutube)
                .addGap(52, 52, 52)
                .addComponent(jButtonSPBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jRBSearchPanelSpofty)
                .addGap(30, 30, 30))
        );
        jSearchPanelBuscasLayout.setVerticalGroup(
            jSearchPanelBuscasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSearchPanelBuscasLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jSearchPanelBuscasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSearchPanelYoutube)
                    .addComponent(jRBSearchPanelSpofty)
                    .addComponent(jButtonSPBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jSearchPanelLayout = new javax.swing.GroupLayout(jSearchPanel);
        jSearchPanel.setLayout(jSearchPanelLayout);
        jSearchPanelLayout.setHorizontalGroup(
            jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSearchPanelBuscas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jSearchPanelLayout.setVerticalGroup(
            jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSearchPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSearchPanelBuscas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jSearchPanel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMainPSearchMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMainPSearchMMouseClicked
        jMainPanel.setVisible(false);
        jSearchPanel.setVisible(true);
    }//GEN-LAST:event_jMainPSearchMMouseClicked

    private void jButtonSPBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSPBuscarMouseEntered
        if(jRBSearchPanelSpofty.isEnabled()){
            
        }else if(jRBSearchPanelYoutube.isEnabled()){
        }
    }//GEN-LAST:event_jButtonSPBuscarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSPBuscar;
    private javax.swing.JButton jMainPSearchM;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JRadioButton jRBSearchPanelSpofty;
    private javax.swing.JRadioButton jRBSearchPanelYoutube;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jSearchPanel;
    private javax.swing.JPanel jSearchPanelBuscas;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
